options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - builds
  - submit
  - --tag=${_REGISTRY_PATH}/${_IMAGE_NAME}

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: 
  - gcloud
  - run
  - deploy
  - ${_IMAGE_NAME}
  - --allow-unauthenticated
  - --cpu=2
  - --memory=2Gi
  - --concurrency=80
  - --max-instances=2
  - --image=${_REGISTRY_PATH}/${_IMAGE_NAME}
  - --region=${_REGION}
  - --set-env-vars=GCP_PROJECT=${_GCP_PROJECT},REDIS_DB=${_REDIS_DB},REDIS_HOST=${_REDIS_HOST},REDIS_PORT=${_REDIS_PORT},BIGQUERY_DATASET=${_BIGQUERY_DATASET},BIGQUERY_TABLE=${_BIGQUERY_TABLE}